import os
import pandas as pd
from docx import Document
from pptx import Presentation
from pptx.util import Inches, Pt
import secrets

UPLOAD_FOLDER = 'uploads'

def ensure_upload_folder():
    if not os.path.exists(UPLOAD_FOLDER):
        os.makedirs(UPLOAD_FOLDER)

def generate_excel(data, filename_prefix="excel"):
    ensure_upload_folder()
    filename = f"{filename_prefix}_{secrets.token_hex(4)}.xlsx"
    filepath = os.path.join(UPLOAD_FOLDER, filename)

    try:
        if isinstance(data, list):
            df = pd.DataFrame(data)
        elif isinstance(data, dict):
            # If it's a dict with list values, it will work.
            # If it's a simple dict, wrap in list.
            try:
                df = pd.DataFrame(data)
            except:
                df = pd.DataFrame([data])
        else:
            df = pd.DataFrame([{"Content": str(data)}])

        df.to_excel(filepath, index=False)
        return {"status": "success", "filename": filename, "filepath": filepath}
    except Exception as e:
        return {"status": "error", "message": str(e)}

def generate_word(content, title="Document", filename_prefix="word"):
    ensure_upload_folder()
    filename = f"{filename_prefix}_{secrets.token_hex(4)}.docx"
    filepath = os.path.join(UPLOAD_FOLDER, filename)

    try:
        doc = Document()
        doc.add_heading(title, 0)

        if isinstance(content, list):
            for p in content:
                doc.add_paragraph(str(p))
        else:
            doc.add_paragraph(str(content))

        doc.save(filepath)
        return {"status": "success", "filename": filename, "filepath": filepath}
    except Exception as e:
        return {"status": "error", "message": str(e)}

def generate_powerpoint(slides_data, title="Presentation", filename_prefix="pptx"):
    """
    slides_data: list of dicts with 'title' and 'content' keys
    """
    ensure_upload_folder()
    filename = f"{filename_prefix}_{secrets.token_hex(4)}.pptx"
    filepath = os.path.join(UPLOAD_FOLDER, filename)

    try:
        prs = Presentation()

        # Title slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title_shape = slide.shapes.title
        subtitle_shape = slide.placeholders[1]
        title_shape.text = title
        subtitle_shape.text = "Generated by Yendoukoa AI"

        # Content slides
        if isinstance(slides_data, list):
            for slide_info in slides_data:
                bullet_slide_layout = prs.slide_layouts[1]
                slide = prs.slides.add_slide(bullet_slide_layout)
                shapes = slide.shapes
                title_shape = shapes.title
                body_shape = shapes.placeholders[1]

                title_shape.text = slide_info.get('title', 'Slide')
                body_shape.text = slide_info.get('content', '')
        else:
             bullet_slide_layout = prs.slide_layouts[1]
             slide = prs.slides.add_slide(bullet_slide_layout)
             slide.shapes.title.text = "Content"
             slide.placeholders[1].text = str(slides_data)

        prs.save(filepath)
        return {"status": "success", "filename": filename, "filepath": filepath}
    except Exception as e:
        return {"status": "error", "message": str(e)}
