from setuptools import setup, find_packages

with open("README.md", "r", encoding="utf-8") as fh:
    long_description = fh.read()

setup(
    name="ai-services-agent",
    version="2.1.1",
    author="Jules",
    author_email="jules@example.com",
    description="A web-based AI agent that can perform several roles to assist with software development and business tasks.",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/GYFX35/AI-services",
    packages=find_packages(),
    py_modules=[
        "app",
        "google_ai",
        "airtable_service",
        "calendly_service",
        "cloudinary_service",
        "elevenlabs_service",
        "emergent_service",
        "flutterwave_service",
        "mailchimp_service",
        "notion_service",
        "office_service",
        "os_service",
        "paystack_service",
        "quickbooks_service",
        "runway_service",
        "tiktok_service",
        "twilio_service",
        "whatsapp_service",
        "xero_service"
    ],
    include_package_data=True,
    install_requires=[
        "Flask[async]",
        "Flask-Babel",
        "Flask-SQLAlchemy",
        "flask-cors>=5.0.0",
        "python-dotenv",
        "requests",
        "beautifulsoup4",
        "lxml",
        "httpx",
        "anyio",
        "sniffio",
        "stripe",
        "facebook-business",
        "google-cloud-aiplatform",
        "google-genai",
        "google-auth",
        "langchain",
        "langchain-google-vertexai",
        "langchain-openai",
        "langchain-anthropic",
        "langchain-nvidia-ai-endpoints",
        "langchain-mistralai",
        "langflow",
        "llama-index",
        "llama-index-llms-nvidia",
        "llama-index-core",
        "azure-ai-inference",
        "azure-core",
        "xero-python",
        "notion-client",
        "firebase-admin",
        "mailchimp-marketing",
        "elevenlabs",
        "cloudinary",
        "runwayml",
        "openpyxl",
        "python-docx",
        "python-pptx",
        "pandas",
        "twilio",
        "pyairtable",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    project_urls={
        "Funding": "https://github.com/sponsors/GYFX35",
        "PSF Sponsors": "https://github.com/sponsors/psf",
        "PSF Donations": "https://www.python.org/psf/donations/",
        "Source": "https://github.com/GYFX35/AI-services",
    },
    python_requires='>=3.6',
)
